const mongoose=require("mongoose");
const DataSchema=mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    phone:{type:String,
        required:true
    },
    email:{
        type:String,
        unique:true,
        required:true,
        lowercase:true
    },
    logo:{
        type:String,
        required:false
    },
    favicon:{
        type:String,
        required:false
    },
    description:{
        type:String,
        required:false
    },
    address:{
        type:String,
        required:false
    },
    public_logo:{
        type:String,
        required:false,
    },
    public_favicon:{
        type:String,
        required:false,
    },
    status:{
        type:String,
        default:"active"
    },
    facebook:{
        type:String,
        required:false,
    },
    twitter:{
        type:String,
        required:false, 
    },
    linkedin:{
        type:String,
        required:false, 
    },
    youtube:{
        type:String,
        required:false, 
    },
    domain:{
        type:String,
        required:true,
    }
},
{
    timestamps:true,
    versionKey:false
})
const SiteSettingModal=mongoose.model('site_settings',DataSchema);
module.exports=SiteSettingModal